/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import com.formdev.flatlaf.extras.FlatSVGIcon;

import BUS.HoaDonBUS;
import DAO.HoaDonDAO;
import DTO.HoaDonDTO;
import GUI.HDon.ThemHD;
import BUS.KhachHangBUS;
import GUI.HDon.CTHoaDon;
import BUS.ChiTietHoaDonBUS;
import DTO.ChiTietHoaDonDTO;
import DTO.SanPhamDTO;

import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class HoaDon extends javax.swing.JPanel {
    private ArrayList<HoaDonDTO> listHoaDon = (new HoaDonBUS()).getAll();
    /**
     * Creates new form SanPham
     */
    public HoaDon() {
        initComponents();
        btn_them.setIcon(new FlatSVGIcon("./GUI/icon/add.svg"));
        btn_sua.setIcon(new FlatSVGIcon("./GUI/icon/edit.svg"));
        btn_xoa.setIcon(new FlatSVGIcon("./GUI/icon/delete.svg"));
        btn_chitiet.setIcon(new FlatSVGIcon("./GUI/icon/detail.svg"));
        btn_lammoi.setIcon(new FlatSVGIcon("./GUI/icon/toolBar_refresh.svg"));
        hienThiListHoaDon(listHoaDon, txt_timkiem.getText());  //keyword
    }

    public void hienThiListHoaDon(ArrayList<HoaDonDTO> listHoaDon, String keyword){
        DefaultTableModel model = (DefaultTableModel) tbl_hoadon.getModel();
        model.setRowCount(0);
        keyword = keyword.trim();
        for (HoaDonDTO hoaDonDTO : listHoaDon){
            int idHoaDon = hoaDonDTO.getIdHoaDon();
            String tenKhachHang = new KhachHangBUS().selectByID(hoaDonDTO.getIdKh()).getHoTen();
            int idNhanVien = hoaDonDTO.getIdNv();
            String ngayLap = hoaDonDTO.getNgayLapHoaDon();
            String tongTien = hoaDonDTO.getTongTien();
            if(keyword.equals("*") || keyword.isBlank()) {
                Object [] row = {
                    idHoaDon,
                    tenKhachHang,
                    idNhanVien,
                    ngayLap,
                    tongTien
                };
                model.addRow(row);
            }
            else if(Integer.toString(idHoaDon).contains(keyword) ||
                    tenKhachHang.toLowerCase().contains(keyword.toLowerCase())){
                Object [] row = {
                    idHoaDon,
                    tenKhachHang,
                    idNhanVien,
                    ngayLap,
                    tongTien
                };
                model.addRow(row);
            }
        }
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i =0;  i< tbl_hoadon.getColumnCount(); i++){
               tbl_hoadon.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_control = new javax.swing.JPanel();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_chitiet = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_timkiem = new javax.swing.JTextField();
        btn_lammoi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_hoadon = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1000, 500));
        setLayout(new java.awt.BorderLayout());

        panel_control.setMinimumSize(new java.awt.Dimension(100, 100));
        panel_control.setPreferredSize(new java.awt.Dimension(1000, 80));

        btn_them.setBackground(new java.awt.Color(255, 255, 255));
        btn_them.setText("Thêm");
        btn_them.setFocusable(false);
        btn_them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themMouseClicked(evt);
            }
        });
        panel_control.add(btn_them);

        btn_sua.setBackground(new java.awt.Color(255, 255, 255));
        btn_sua.setText("Sửa");
        btn_sua.setEnabled(false);
        btn_sua.setFocusable(false);
        panel_control.add(btn_sua);

        btn_xoa.setBackground(new java.awt.Color(255, 255, 255));
        btn_xoa.setText("Xóa");
        btn_xoa.setEnabled(false);
        btn_xoa.setFocusable(false);
        panel_control.add(btn_xoa);

        btn_chitiet.setBackground(new java.awt.Color(255, 255, 255));
        btn_chitiet.setText("Chi tiết");
        btn_chitiet.setFocusable(false);
        btn_chitiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_chitietMouseClicked(evt);
            }
        });
        panel_control.add(btn_chitiet);

        jLabel1.setText("Tìm kiếm");
        panel_control.add(jLabel1);

        txt_timkiem.setText("*");
        txt_timkiem.setPreferredSize(new java.awt.Dimension(100, 30));
        panel_control.add(txt_timkiem);

        btn_lammoi.setBackground(new java.awt.Color(255, 255, 255));
        btn_lammoi.setText("Làm mới");
        btn_lammoi.setFocusable(false);
        btn_lammoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lammoiMouseClicked(evt);
            }
        });
        panel_control.add(btn_lammoi);

        add(panel_control, java.awt.BorderLayout.PAGE_START);

        tbl_hoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Tên khách hàng", "Mã nhân viên", "Ngày lập", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_hoadon.setPreferredSize(new java.awt.Dimension(1200, 800));
        jScrollPane2.setViewportView(tbl_hoadon);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_chitietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_chitietMouseClicked
        int slctedRow = tbl_hoadon.getSelectedRow();
        if (slctedRow != -1) {
            Object idHD = tbl_hoadon.getValueAt(slctedRow, 0);
            if (idHD instanceof Integer int_idHD) {
                ArrayList<ChiTietHoaDonDTO> cthdList = new ChiTietHoaDonBUS().getAllByID(int_idHD);
                CTHoaDon ctHD = new CTHoaDon(cthdList);
                ctHD.setVisible(true);
            }          
        }
        else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn hóa đơn để xem chi tiết");
        }
    }//GEN-LAST:event_btn_chitietMouseClicked

    private void btn_themMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themMouseClicked
        ThemHD themHD = new ThemHD();
        themHD.setVisible(true);
    }//GEN-LAST:event_btn_themMouseClicked

    private void btn_lammoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lammoiMouseClicked
        this.listHoaDon = new HoaDonBUS().getAll();
        hienThiListHoaDon(listHoaDon, txt_timkiem.getText());
    }//GEN-LAST:event_btn_lammoiMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chitiet;
    private javax.swing.JButton btn_lammoi;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel_control;
    private javax.swing.JTable tbl_hoadon;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables
}
