/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.HDon;

import BUS.SanPhamBUS;
import DTO.SanPhamDTO;
import DTO.ChiTietHoaDonDTO;
import GUI.HoaDon;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.SwingConstants;
/**
 *
 * @author Administrator
 */
public class CTHoaDon extends javax.swing.JFrame {
    /**
     * Creates new form CTHoaDon
     */
    
    private javax.swing.JFrame parentFrame;
    private ArrayList<ChiTietHoaDonDTO> listCTHD = new ArrayList<>();
    
    public CTHoaDon(){
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public CTHoaDon(javax.swing.JFrame parentFrame, ArrayList<ChiTietHoaDonDTO> listCTHD) { //xem chi tiết hóa đơn chưa tạo
        initComponents();
        setLocationRelativeTo(null);
        hienThiListChiTiet(listCTHD);
        this.parentFrame = parentFrame;
        this.parentFrame.setVisible(false);
        this.listCTHD = listCTHD;
    }

    public CTHoaDon(ArrayList<ChiTietHoaDonDTO> listCTHD) {             //nếu đây là xem chi tiết hóa đơn đã tạo
        initComponents();
        btn_sua.setEnabled(false);
        btn_xoa.setEnabled(false);
        hienThiListChiTiet(listCTHD);
        this.listCTHD = listCTHD;
    }
    
    private void hienThiListChiTiet(ArrayList<ChiTietHoaDonDTO> listCTHD){  //sửa 2 cột sau
        DefaultTableModel model = (DefaultTableModel) tbl_ctHD.getModel();
        model.setRowCount(0);
        for (ChiTietHoaDonDTO cthdDTO : listCTHD){
            SanPhamDTO spDTO = new SanPhamBUS().selectByID(cthdDTO.getIdSach());
            cthdDTO.setGiaBan();
            Object [] row = {
                spDTO.getTenSanPham(),          //D
                cthdDTO.getSoLuongMua(),         //D    
                spDTO.getDonGia(),          //giá 1 quyển
                cthdDTO.getGiaBan()         //giá quyển * số lượng
            };
            model.addRow(row);
        }
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i =0;  i< tbl_ctHD.getColumnCount(); i++){
               tbl_ctHD.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        lbl_title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ctHD = new javax.swing.JTable();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_xong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(204, 255, 204));

        lbl_title.setBackground(new java.awt.Color(255, 51, 51));
        lbl_title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("Chi Tiết Hóa Đơn");

        tbl_ctHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên sách", "Số lượng", "Giá (1 cuốn)", "Tổng giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_ctHD);

        btn_sua.setText("Sửa số lượng");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_xong.setText("Xong");
        btn_xong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_xongMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(btn_sua)
                .addGap(33, 33, 33)
                .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btn_xong, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xong, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btn_xongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_xongMousePressed
        try {
            this.parentFrame.setVisible(true);
        } 
        catch (Exception e){}
        finally {
            this.dispose();
        }    
    }//GEN-LAST:event_btn_xongMousePressed
       
    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        try {
            int slctedRow = tbl_ctHD.getSelectedRow();
            int soLuong = (Integer) tbl_ctHD.getValueAt(slctedRow, 1);

                int soLuongMoi = Integer.parseInt(JOptionPane.showInputDialog("Nhập số lượng mới", soLuong));
                if (soLuongMoi > 0) {
                    this.listCTHD.get(slctedRow).setSoLuongMua(soLuongMoi);
                    tbl_ctHD.setValueAt(soLuongMoi, slctedRow, 1);
                    this.listCTHD.get(slctedRow).setGiaBan();
                    hienThiListChiTiet(listCTHD);
    //                tbl_ctHD.setValueAt(this.listCTHD.get(slctedRow).getGiaBan(), slctedRow, 3);
                    JOptionPane.showMessageDialog(null, "Sửa thành công");
                }
                else {
                    JOptionPane.showMessageDialog(null, "Sửa thất bại");
                }
            }      
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Sửa thất bại");
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        try{    
            int confirm = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa?");
            if (confirm == JOptionPane.YES_OPTION) {
                Iterator it = this.listCTHD.iterator();
                int slctedRow = tbl_ctHD.getSelectedRow();
                String tenSach = (String) tbl_ctHD.getValueAt(slctedRow, 0); //lấy tên sách
                while (it.hasNext()) {
                    ChiTietHoaDonDTO cthd = (ChiTietHoaDonDTO) it.next();
                    String tSach = new SanPhamBUS().selectByID(cthd.getIdSach()).getTenSanPham();
                    if (tSach.equals(tenSach)) {
                        it.remove();
                        hienThiListChiTiet(this.listCTHD);
                        break;
                    }
                }
            }   
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Xóa thất bại");
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CTHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CTHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CTHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CTHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CTHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JButton btn_xong;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_title;
    private java.awt.Panel panel1;
    private javax.swing.JTable tbl_ctHD;
    // End of variables declaration//GEN-END:variables
}
