/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.HDon;

import BUS.ChiTietHoaDonBUS;
import BUS.HoaDonBUS;
import BUS.KhachHangBUS;
import BUS.SanPhamBUS;
import BUS.TaiKhoanBUS;
import DTO.ChiTietHoaDonDTO;
import DTO.HoaDonDTO;
import DTO.KhachHangDTO;
import DTO.SanPhamDTO;
import DTO.TaiKhoanDTO;
import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Administrator
 */
public class ThemHD extends javax.swing.JFrame {
    private final int maHD = new HoaDonBUS().getAll().size() + 1;
    private ArrayList<ChiTietHoaDonDTO> listCTHD = new ArrayList<>();
    private ArrayList<SanPhamDTO> listSanPham = new ArrayList<>();
    /**
     * Creates new form ThemHD
     */
    public ThemHD() {
        initComponents();
        initComponentsValue();
        loadCboxNhanVien();
        loadCboxKhachHang();
    }
    
    private void initComponentsValue(){
        txt_maHD.setText(Integer.toString(maHD));
        
        LocalDateTime ngayTao = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        txt_ngayLap.setText(ngayTao.format(formatter));             //TODO
    }
    
    private void loadCboxNhanVien(){
        TaiKhoanBUS tkBUS = new TaiKhoanBUS();
        for (TaiKhoanDTO tkDTO : tkBUS.getAll()) {
            cbox_NhanVien.addItem(tkDTO.getIdNhanVien() + " - " + tkDTO.getTenDangNhap());
        }
    }
    
    private void loadCboxKhachHang(){
        KhachHangBUS khBUS = new KhachHangBUS();
        for (KhachHangDTO khDTO : khBUS.getAll()) {
            cbox_KhachHang.addItem(khDTO.getIdKhachHang() + " - " + khDTO.getHoTen());
        }
    }
    
    private void loadCboxSach(String keyword) {         //cbox_sach
        SanPhamBUS sanPhamBus = new SanPhamBUS();
        cbox_sach.removeAllItems();
        for (SanPhamDTO sp : sanPhamBus.getAll()) {  
            if(keyword.equals("*")){
                cbox_sach.addItem(sp.getTenSanPham());
                this.listSanPham.add(sp);
            }
            else if (sp.getTenSanPham().toUpperCase().contains(keyword.toUpperCase())) {                    
                cbox_sach.addItem(sp.getTenSanPham());
                this.listSanPham.add(sp);
            }
        }    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        pnl_lower = new javax.swing.JPanel();
        cbox_sach = new javax.swing.JComboBox<>();
        spnr_soLuong = new javax.swing.JSpinner();
        btn_themSach = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_maHD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_ngayLap = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_tongTien = new javax.swing.JTextField();
        btn_xemCT = new javax.swing.JButton();
        btn_themHD = new javax.swing.JButton();
        btn_huyHD = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_timSach = new javax.swing.JTextPane();
        btn_timSach = new javax.swing.JButton();
        cbox_NhanVien = new javax.swing.JComboBox<>();
        cbox_KhachHang = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlTop.setBackground(new java.awt.Color(204, 255, 204));

        lbl_title.setBackground(new java.awt.Color(255, 51, 51));
        lbl_title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("Thêm Hóa Đơn");

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pnl_lower.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnl_lowerMouseMoved(evt);
            }
        });
        pnl_lower.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pnl_lowerFocusGained(evt);
            }
        });

        spnr_soLuong.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        btn_themSach.setText("Thêm");
        btn_themSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themSachMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Chọn sách");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Số lượng");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tên khách hàng");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Mã hóa đơn");

        txt_maHD.setEnabled(false);
        txt_maHD.setPreferredSize(new java.awt.Dimension(64, 32));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Mã nhân viên xử lý");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Ngày lập");

        txt_ngayLap.setEnabled(false);
        txt_ngayLap.setPreferredSize(new java.awt.Dimension(300, 32));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Tổng tiền");

        txt_tongTien.setEnabled(false);
        txt_tongTien.setMinimumSize(new java.awt.Dimension(64, 32));
        txt_tongTien.setPreferredSize(new java.awt.Dimension(73, 32));

        btn_xemCT.setText("Chi tiết hóa đơn");
        btn_xemCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_xemCTMousePressed(evt);
            }
        });

        btn_themHD.setText("Thêm");
        btn_themHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themHDMouseClicked(evt);
            }
        });

        btn_huyHD.setText("Hủy");
        btn_huyHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_huyHDMouseClicked(evt);
            }
        });

        txt_timSach.setText("*");
        jScrollPane1.setViewportView(txt_timSach);

        btn_timSach.setText("Tìm");
        btn_timSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_timSachMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_lowerLayout = new javax.swing.GroupLayout(pnl_lower);
        pnl_lower.setLayout(pnl_lowerLayout);
        pnl_lowerLayout.setHorizontalGroup(
            pnl_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_lowerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnl_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_lowerLayout.createSequentialGroup()
                        .addGroup(pnl_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbox_sach, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnl_lowerLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(8, 8, 8)
                                    .addComponent(jScrollPane1)))
                            .addComponent(jLabel2)
                            .addGroup(pnl_lowerLayout.createSequentialGroup()
                                .addComponent(spnr_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(btn_themSach)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_xemCT)))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tongTien, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addGroup(pnl_lowerLayout.createSequentialGroup()
                                .addGroup(pnl_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(btn_timSach))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_lowerLayout.createSequentialGroup()
                        .addGroup(pnl_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnl_lowerLayout.createSequentialGroup()
                                .addGroup(pnl_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_maHD, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(292, 292, 292)
                                .addGroup(pnl_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_lowerLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(cbox_KhachHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_lowerLayout.createSequentialGroup()
                                .addGroup(pnl_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_lowerLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(cbox_NhanVien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(pnl_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txt_ngayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27))))
            .addGroup(pnl_lowerLayout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(btn_themHD, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btn_huyHD, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl_lowerLayout.setVerticalGroup(
            pnl_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_lowerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnl_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_maHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbox_KhachHang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_lowerLayout.createSequentialGroup()
                        .addGroup(pnl_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ngayLap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbox_NhanVien))
                        .addGap(32, 32, 32)
                        .addGroup(pnl_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_lowerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_timSach)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbox_sach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnl_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_lowerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnl_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_lowerLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_tongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_lowerLayout.createSequentialGroup()
                                .addGroup(pnl_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_huyHD, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_themHD, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(pnl_lowerLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_lowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnr_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_themSach)
                            .addComponent(btn_xemCT)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_lower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_lower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btn_timSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_timSachMouseClicked
        loadCboxSach(txt_timSach.getText());
    }//GEN-LAST:event_btn_timSachMouseClicked

    private void btn_xemCTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_xemCTMousePressed
        if(this.listCTHD.size() == 0) {
            JOptionPane.showMessageDialog(null, "Chưa có sách nào trong hóa đơn để xem chi tiết");
        }
        else {
            CTHoaDon ctHoaDon = new CTHoaDon(this, this.listCTHD);         
            ctHoaDon.setVisible(true);
        }        
    }//GEN-LAST:event_btn_xemCTMousePressed

    private void btn_huyHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_huyHDMouseClicked
        int result = JOptionPane.showConfirmDialog(rootPane, "Xác nhận hủy?");
        if (result == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btn_huyHDMouseClicked

    private boolean kiemTraCTHD(String s) {     //kiểm tra trùng trong CTHD
        boolean flag = false;
        for (ChiTietHoaDonDTO cthd : this.listCTHD) {
            String tenSach = new SanPhamBUS().selectByID(cthd.getIdSach()).getTenSanPham();
            if (s.equals(tenSach)) {
                flag = true;
                break;
            }
        }
        return flag;
    }
    
    private void btn_themSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themSachMouseClicked
        try { //tránh trường hợp bấm tìm luôn
            String selectedBookName =  cbox_sach.getSelectedItem().toString();
            int selectedAmount = (Integer) spnr_soLuong.getValue();
            if(selectedBookName.isBlank()){
                JOptionPane.showMessageDialog(null, "Chưa có sách nào được chọn");
            }      
            else if(this.kiemTraCTHD(selectedBookName)) {
                JOptionPane.showMessageDialog(null, "Trong hóa đơn đã có sách này");
            }
            else {
                for (SanPhamDTO sp : this.listSanPham) {
                    if(sp.getTenSanPham().equals(selectedBookName)) {
                        ChiTietHoaDonDTO ctHoaDon = new ChiTietHoaDonDTO(maHD, sp.getIdSanPham(), selectedAmount);
                        ctHoaDon.setGiaBan();
                        this.listCTHD.add(ctHoaDon);
                        JOptionPane.showMessageDialog(null, "Thêm thành công " + selectedAmount + " bản của sách " + selectedBookName);
                        txt_tongTien.setText(ChiTietHoaDonBUS.tinhTongTien(this.listCTHD));
                    }
                }
            }
        }
        catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn sách trước khi thêm");
        } 
    }//GEN-LAST:event_btn_themSachMouseClicked

    private void pnl_lowerMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_lowerMouseMoved
        txt_tongTien.setText(ChiTietHoaDonBUS.tinhTongTien(this.listCTHD));
    }//GEN-LAST:event_pnl_lowerMouseMoved

    private void pnl_lowerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnl_lowerFocusGained
        txt_tongTien.setText(ChiTietHoaDonBUS.tinhTongTien(this.listCTHD));
    }//GEN-LAST:event_pnl_lowerFocusGained

    private void btn_themHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themHDMouseClicked
        if(this.listCTHD.isEmpty()){
            JOptionPane.showMessageDialog(null, "Vui lòng không để trống thông tin");
        }
        else{
            int idHD = this.maHD;
            int idKH = Integer.parseInt(((String) cbox_KhachHang.getSelectedItem()).split("-")[0].trim());
            int idNV = Integer.parseInt(((String) cbox_NhanVien.getSelectedItem()).split("-")[0].trim()); //split bằng - rồi trim khoảng trắng
            String ngayLap = txt_ngayLap.getText();
            String tongTien = txt_tongTien.getText();
            int trangThai = 1;          //TODO CHANGE THIS
            HoaDonDTO hoaDon = new HoaDonDTO(idHD, ngayLap, tongTien, idNV, idKH, trangThai);
            HoaDonBUS hdBUS = new HoaDonBUS();
            boolean flag_themHD = hdBUS.getHdDAO().addHoaDon(hoaDon);
    //      ============================THÊM CHI TIẾT HĐ========================================
            ChiTietHoaDonBUS cthdBUS = new ChiTietHoaDonBUS();
            boolean flag_themCTHD = cthdBUS.getCthdDAO().addCTHD(this.listCTHD);
            if(flag_themHD && flag_themCTHD) {
                JOptionPane.showMessageDialog(null, "Thêm thành công");
            }
            else if (flag_themHD == false){
                JOptionPane.showMessageDialog(null, "Đã có lỗi xảy ra trong quá trình thêm hóa đơn");
            }
            else if (flag_themCTHD == false){
                JOptionPane.showMessageDialog(null, "Đã có lỗi xảy ra trong quá trình thêm chi tiết hóa đơn");
            }
            this.dispose();
        }
    }//GEN-LAST:event_btn_themHDMouseClicked
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemHD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_huyHD;
    private javax.swing.JButton btn_themHD;
    private javax.swing.JButton btn_themSach;
    private javax.swing.JButton btn_timSach;
    private javax.swing.JButton btn_xemCT;
    private javax.swing.JComboBox<String> cbox_KhachHang;
    private javax.swing.JComboBox<String> cbox_NhanVien;
    private javax.swing.JComboBox<String> cbox_sach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JPanel pnl_lower;
    private javax.swing.JSpinner spnr_soLuong;
    private javax.swing.JTextField txt_maHD;
    private javax.swing.JTextField txt_ngayLap;
    private javax.swing.JTextPane txt_timSach;
    private javax.swing.JTextField txt_tongTien;
    // End of variables declaration//GEN-END:variables
}
